name: Deploy to Google Apps Script

on:
  push:
    branches: [main]
    paths:
      - "backlog-sheets-integration/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Create clasp credentials
        run: echo "$CLASPRC_JSON" > ~/.clasprc.json
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
        
      - name: Push to Google Apps Script
        run: |
          cd backlog-sheets-integration
          clasp push --force

      - name: Deploy to production
        run: clasp deploy --description "Auto-deploy from GitHub Actions"
        working-directory: ./backlog-sheets-integration
